### ISSUE TITLE
How to include this feature in the piTrezor project? Heneault / yocto-pitrezor

### ISSUE THREAD

**Issue by UncleSamKuia** [ushiboy/waveshare-1.3inch-lcd-hat-240x240#2]
Hello, I'm new here on github and I would like to have help to include this screen in the options of the piTrezor project, because there is ... thank you very much right now.

**Comment by ushiboy** [comment]
Hi, thanks for the offer.
But this repository has been suspended for a long time, and there are no plans to reopen it yet.
Sorry.
